In [1]:
import pandas as pd

In [2]:
d, m, y = '01', '03', '2024'

In [11]:
df = pd.read_parquet(f"./sunt/{y}-{m}-{d}/output/trips_time-series_{d}-{m}-{y}_{d}-{m}-{y}.parquet")
df

,linha_atend,linha,cod_ate,sentido,shape,ordem,stop_id,lat,lon,distancias,...,tempo_parada,duracao,tempo_total,tempo_parada_acum,duracao_acum,distancia,dis_acum,vm,vm_acum,type
0,123101_57892,123101,57892,I,57892_I,1,44782944,-12.942813,-38.438602,0.000,...,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,bus
1,123101_57892,123101,57892,I,57892_I,2,44784618,-12.939712,-38.438862,0.449,...,7.0,80.0,87.0,7.0,80.000000,0.345999,0.000000,15.569937,0.000000,bus
2,123101_57892,123101,57892,I,57892_I,3,44784340,-12.938302,-38.439884,0.126,...,36.0,21.0,57.0,43.0,101.000000,0.191938,0.345999,32.903659,12.332624,bus
3,123101_57892,123101,57892,I,57892_I,4,44782337,-12.935150,-38.440578,0.523,...,32.0,129.0,161.0,75.0,230.000000,0.358460,0.537937,10.003548,8.419877,bus
4,123101_57892,123101,57892,I,57892_I,5,44784470,-12.937017,-38.437576,0.417,...,17.0,47.0,64.0,92.0,277.000000,0.385962,0.896397,29.563075,11.649926,bus
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
739365,115701_53715,115701,53715,V,53715_V,23,193795241,-12.974805,-38.481640,0.470,...,32.0,91.0,123.0,384.0,1435.999999,0.081986,4.986591,3.243383,12.501203,bus
739366,115701_53715,115701,53715,V,53715_V,24,193815791,-12.976386,-38.481007,0.626,...,8.0,115.0,123.0,392.0,1550.999999,0.188735,5.068576,5.908234,11.764587,bus
739367,115701_53715,115701,53715,V,53715_V,25,193815792,-12.975221,-38.479652,0.190,...,11.0,41.0,52.0,403.0,1591.999999,0.195766,5.257312,17.189191,11.888393,bus
739368,115701_53715,115701,53715,V,53715_V,26,45834832,-12.972300,-38.479965,0.599,...,7.0,83.0,90.0,410.0,1674.999999,0.326576,5.453077,14.164747,11.720047,bus
739369,115701_53715,115701,53715,V,53715_V,27,66292237,-12.969787,-38.478218,0.998,...,0.0,143.0,143.0,410.0,1817.999999,0.337519,5.779653,8.496978,11.444858,bus

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 739370 entries, 0 to 739369
Data columns (total 31 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   linha_atend        739370 non-null  object
 1   linha              739370 non-null  object
 2   cod_ate            739370 non-null  object
 3   sentido            739370 non-null  object
 4   shape              739370 non-null  object
 5   ordem              739370 non-null  int64
 6   stop_id            739370 non-null  object
 7   lat                739370 non-null  float64
 8   lon                739370 non-null  float64
 9   distancias         739370 non-null  float64
 10  acumulado          739370 non-null  float64
 11  posicao            739370 non-null  object
 12  veiculo            739266 non-null  object
 13  trip               739266 non-null  float64
 14  trip_id            739266 non-null  object
 15  inicio_viagem      739266 non-null  datetime64[ns]
 16  fim_viagem         739266 non-null  datetime64[ns]
 17  set                739266 non-null  object
 18  hora_ponto         739370 non-null  datetime64[ns]
 19  saida              739370 non-null  datetime64[ns]
 20  fill               739370 non-null  bool
 21  tempo_parada       739370 non-null  float64
 22  duracao            739370 non-null  float64
 23  tempo_total        739370 non-null  float64
 24  tempo_parada_acum  739370 non-null  float64
 25  duracao_acum       739370 non-null  float64
 26  distancia          739370 non-null  float64
 27  dis_acum           739370 non-null  float64
 28  vm                 739282 non-null  float64
 29  vm_acum            739045 non-null  float64
 30  type               739370 non-null  object
dtypes: bool(1), datetime64[ns](4), float64(14), int64(1), object(11)
memory usage: 169.9+ MB